name: Run Ruby Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      CI: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.1'
    - name: Install dependencies
      run: bundle install
    - name: Run Rubocop linter
      run: bundle exec rake rubocop
    - name: Run tests
      run: bundle exec rake test
    - name: Generate Documentation
      run: bundle exec yard
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        badge: true
        filename: coverage/coverage.xml
        format: markdown
        output: both
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
  "Increment-Version":
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"
      - run: echo OLD_VERSION=$(ruby -e "require_relative('worklog/version'); puts current_version") >> $GITHUB_ENV
      - run: echo NEW_VERSION=$(ruby -e "require_relative('worklog/version'); puts increment_version(current_version)") >> $GITHUB_ENV
      - run: echo "${OLD_VERSION} -> ${NEW_VERSION}"
      - run: echo ${NEW_VERSION} > .version
      - name: Update version
        uses: test-room-7/action-update-file@v1
        with:
          file-path: .version
          commit-msg: [skip ci] Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # - run: git tag ${NEW_VERSION}
      # - run: git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags
      # - run: git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --tags