name: Run Ruby Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.1'

    - name: Install dependencies
      run: bundle install

    - name: Run Rubocop linter
      run: bundle exec rake rubocop

    - name: Run tests
      run: bundle exec rake test
