name: Run Ruby Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      CI: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.3'
    - name: Prepare temp directory
      run: mkdir -p /tmp/worklog_test
    - name: Install dependencies
      run: bundle install
    - name: Run Rubocop linter
      run: bundle exec rake rubocop
    - name: Run tests
      run: bundle exec rake test
    - name: Generate Documentation
      run: bundle exec yard
    - name: "Build Gem"
      run: gem build
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        badge: true
        filename: coverage/coverage.xml
        format: markdown
        output: both
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
